name: Automatic tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build and test
        run: ./mvnw clean test